# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51d989a1bb2d55bb422e480081fecc3ccbcbe73203fe546a943eb557e6cfea1e17563c7c2313a28f8252b2bbbfa7da828ac361cdcd0ac376ddaa5f87058e5e03

test:
  secret_key_base: 7432e3df044b37d14dd926d2c8d4cfbf7e4550a1106d6dee823c84ae5ebe7fb57a909d080f7a9249c2465ca0ef886f3c03f10c1fd2adb2e0dd565f1699f11b13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
